### PR TITLE
Add T2UHP AC600 usb device id

### PR DESCRIPTION
**Pull request by murat1985**
Simple addition for T2UHP AC600 to make driver recognize it.
Tested on armbian (armv7l Linux kernel 4.11.3). Probably works on x86 and Raspberry PI as well.

Works in sta mode. Relatively stable.

### CODE REVIEW

**Comment by obernardovieira** [comment]
I think, you should also update the README file (update "Devices recognized by module")

**Comment by murat1985** [comment]
Hi @obernardovieira, 

Sorry forgot about README, updated it is well and cleaned up list formatting if you don't mind :) 

Thanks

**Comment by obernardovieira** [comment]
I don't mind @murat1985, it was just a suggestion to make things more clear to others.
And thank you btw 👍

**Comment by xtknight** [comment]
Thank you! merged

**Pull request merged**
