### PR TITLE
Fixed compil for Linux >= 4.15

### PR DESCRIPTION
**Pull request by Viish**
Hi,

This PR fixes the compilation on Linux version 4.15 and newer.
Fix is mostly the same as the one in https://github.com/evgeni/tp_smapi/issues/31

Thanks a lot for your work, I wouldn't have WiFi on my computer if it wasn't for you !

Best regards.

### CODE REVIEW

**Comment by Dumonu** [comment]
Have you gotten this fix to work? I'm working on a fix myself and when I looked into it, it looked like there was a fundamental change to the way the kernel handles timers, such that it looked like it would take a rework of BUILD_TIMER_FUNCTION.

**Comment by Dumonu** [comment]
I just compiled and installed this version. I cannot see my wifi card in the output of `ip link`. This is the same issue I'm running into with my current version of the fix.

**Comment by Viish** [comment]
This fix works fine for my TP-Link T2UH on my desktop running KaOS (an OS based on Arch) with kernel 4.15.

**Comment by Dumonu** [comment]
Interesting. That's the same card I have and I'm running Arch, so from what I can tell, it should work. `lsusb` has `Bus 001 Device 002: ID 148f:761a Ralink Technology, Corp. MT7610U ("Archer T2U" 2.4G+5G WLAN Adapter` in its output.

**Comment by Dumonu** [comment]
Ah. I've poked around and it looks like something in this driver is looking for the symbols `vfs_write` and `vfs_read` and they don't exist.

**Comment by Dumonu** [comment]
OK. So my issue was in the `vfs_write` and `vfs_read` calls. I have no idea why it's an issue. I commented out those lines, replacing them with dummy lines and now it runs perfectly fine. I'll look into why they might be having an issue tomorrow. I guess I was overthinking the fix.

**Comment by Dumonu** [comment]
OK. Never mind. I just looked into it. I get nerdsniped easily. `vfs_read` and `vfs_write` are deprecated and have been unexported. The new version is `kernel_read` and `kernel_write`. I'll look into setting up preprocessor directives for this change and set up a pull request.

**Comment by jneumaier** [comment]
Please merge those commits. Came up with the same solution which was quite some effort for me :-) Just wanted to create a pull request and found the same fix here.
Thanks to all contributors!

**Comment by Jibtchay** [comment]
Hi, 
I've been trying to make my TP-Link T2UH work on my virtual machine kali linux (kernel 4.15.0) but I can't manage to install the drivers. I finally ended up here after looking for solutions. I have wondering how to apply you fixes about compilations on kernel 4.15. Do I have to copy the files to the correspondant location ? If yes, I tried it but it didn't work. Can you help me please ? @Viish

**Comment by jneumaier** [comment]
@Jibtchay You can clone the master of Viish's fork from his repository: https://github.com/Viish/mt7610u-linksys-ae6000-wifi-fixes
4.15 compile fixes are already merged there.

**Comment by Jibtchay** [comment]
@jneumaier It worked, thanks ! But whenever I try to connect to my network, the VM freezes after a few sec, do you have an idea why it's happening ?

**Comment by jneumaier** [comment]
@Jibtchay No idea, sorry. I also had freezes with other drivers but with different error logs. I am also using a Raspberry Pi, so this might be difficult to compare.

**Comment by Dumonu** [comment]
Does the output from `lsusb` contain the card with a proper vendor name and description?

**Comment by Dumonu** [comment]
Hmm. That's the proper output of `lsusb`, so that's not the issue. I tried finding the definition of `RTUSB_VendorRequest()`, but I could only find its declaration in a header. It doesn't get the definition from the kernel, which I checked. If anyone knows where to find that function, that'd probably shed some light on this.

**Comment by Jibtchay** [comment]
I also found this from "systemctl status NetWorkManager.service:

 systemctl status NetworkManager.service
● NetworkManager.service - Network Manager
   Loaded: loaded (/lib/systemd/system/NetworkManager.service; enabled; vendor p
   Active: activating (start) since Tue 2018-05-29 17:30:41 CEST; 21s ago
     Docs: man:NetworkManager(8)
 Main PID: 2202 (NetworkManager)
    Tasks: 4 (limit: 2353)
   Memory: 17.3M
   CGroup: /system.slice/NetworkManager.service
           ├─ 482 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helpe
           ├─2189 /usr/sbin/NetworkManager --no-daemon
           └─2202 /usr/sbin/NetworkManager --no-daemon

mai 29 17:30:41 me systemd[1]: NetworkManager.service: Service hold-off time ove
mai 29 17:30:41 me systemd[1]: NetworkManager.service: Scheduled restart job, re
mai 29 17:30:41 me systemd[1]: Stopped Network Manager.
mai 29 17:30:41 me systemd[1]: NetworkManager.service: Found left-over process 4
mai 29 17:30:41 me systemd[1]: This usually indicates unclean termination of a p
mai 29 17:30:41 me systemd[1]: NetworkManager.service: Found left-over process 2
mai 29 17:30:41 me systemd[1]: This usually indicates unclean termination of a p
mai 29 17:30:41 me systemd[1]: Starting Network Manager...
mai 29 17:30:41 me NetworkManager[2202]: <info>  [1527607841.8629] NetworkManage
mai 29 17:30:41 me NetworkManager[2202]: <info>  [1527607841.8630] Read config: 

Don't really know what it means

**Comment by tinhtrilac** [comment]
Thanks
I was able to build and install, but I cannot see any network.
Do i have anything else?

**Pull request merged**
